version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          command: yarn run cy:report
          record: true
          store_artifacts: true
