
version: 2

jobs:
  build:
    working_directory: ~/feature/test/package.json
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
  test:
    working_directory: ~/
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - run:
          name: Running cypress tests
          command: npm run cy:report

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
