version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      build: 'npm install'
          requires:
            - cypress/install
          yarn: true
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines
