version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build-test-and-notify:
    executor:
      name: cypress/base-14
    steps:
      - checkout
workflows:
  build-and-notify:
    jobs:
      - cypress/run:
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          post-steps:
            - store_test_results:
                path: cypress/results
      - build-test-and-notify
