version: 2
jobs:
  build:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      - run: pwd
      - run: ls
  test:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - run:
          name: Running cypress tests
          command: yarn cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
