  
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0

workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - run: 
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge cypress/reports/mocha/*.json > mochareports/report.json 
            - run: 
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports
